### ISSUE TITLE
Using a modal to show the video instead of embedding all the videos 

### ISSUE THREAD

**Issue by omar2205** [CodingGarden/listd#106]
### Describe the problem

Currently, we embed all the iframes, and the player is small.

### Describe the proposed solution

User click the video and it opens a modal to 1) embed the iframe 2) play the video

### Have you checked if this issue has already been raised?

- [X] I did not find any similar issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishalbalaji** [comment]
Alternatively, I would suggest a **Theater Mode** toggle, which just causes the iframe to resize to the full width of the screen.

**Comment by w3cj** [comment]
Going with theater mode / full screen video.
