### ISSUE TITLE
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2

### ISSUE THREAD

**Issue by Hex09AF** [CodingGarden/listd#110]
### Describe the problem

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/118161628/232464213-2dd4bb51-724d-452d-997c-fbd2d85fd4c2.png">

Resolved the warning by using node v16

### Describe the proposed solution

Following the basic setup in https://github.com/actions/setup-node

We can resolved the warning using the below code in our github workflows checks.yaml file

```bash
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
```

### Have you checked if this issue has already been raised?

- [X] I did not find any similar issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by w3cj** [comment]
Updated!
