### ISSUE TITLE
Let's use `header`/`footer` tags only for main header and footer

### ISSUE THREAD

**Issue by babakfp** [CodingGarden/listd#140]
It responded:

"Yes, it's perfectly okay to use <div> elements instead of <header> and <footer> elements if you prefer not to use <header> and <footer> in places other than the main header and footer of your document. <div> elements are generic containers that do not carry any specific semantic meaning, which means they can be used more flexibly for styling and structuring your content as you see fit.

Using <div> elements is a common practice when you want to create custom layouts and structures that don't align with the traditional <header> and <footer> semantics. This approach provides you with greater flexibility in how you design and style your web page or components.

Ultimately, your choice should depend on your design preferences, project requirements, and the semantics you want to convey. As long as your HTML structure makes sense within the context of your project and meets your design goals, you can use <div> elements without any issues."

😂

So, I never seen this before and I don't like it.

**Comment by w3cj** [comment]
We are using semantic tag names.
