### ISSUE TITLE
`sourcemap-codec` dependency is deprecated

### ISSUE THREAD

**Issue by gabrielforster** [CodingGarden/listd#18]
### Describe the bug

When running `npm install` npm warns that this package is deprecated.
```bash
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

This can be easily fixed by installing the npm recommendation [@jridgewell/sourcemap-codec](https://www.npmjs.com/package/@jridgewell/sourcemap-codec)

### Screenshots

![image](https://user-images.githubusercontent.com/51389447/216734509-a888f286-334c-4364-8273-64ea9c0b9356.png)

### Reproduction

Just fresh clone the repo and run `npm install` script

### Logs

```shell
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

**Comment by w3cj** [comment]
Thanks! Fixed in c4939ebce2ed01a955f5bd026cc6aac4295b0b6b
