### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by gabrielforster** [CodingGarden/listd#25]
### Describe the problem

As a dev that wants do contribute to this project, I think that would be great to have a pull request template.
Something like this...

---
### Description about your change.
In this pr I did some changes on the main page.
### Info that the code reviewer should know about when reviewing this code.
To reproduce my feature, run the project locally and go to the main page.
### Screenshots if needed.
![image](https://user-images.githubusercontent.com/51389447/216769338-10d9776c-cb8d-4da1-975b-07960a92e14c.png)

**Comment by w3cj** [comment]
Closed by #34
