### ISSUE TITLE
Tracking settings.json prevents contributors from having custom workspace settings

### ISSUE THREAD

**Issue by cesarnml** [CodingGarden/listd#40]
### Describe the problem

Committing `.vscode/settings.json` to source control removes the ability for contributors to have their own custom Workspace Settings while working on `listd`. 

For example, I would like to use the [peacock extension](https://www.peacockcode.dev/) to jazz up vscode's color scheme, but to do so, the extension must modify workspace settings.

### Describe the proposed solution

Add `vscode/settings.json` to .gitignore. 

Rename `.vscode/settings.json` to `.vscode/settings.json.default` and add a blurb in the project README.md to encourage contributors to manually adopt the project's suggested default workspace settings.

[solution reference](https://stackoverflow.com/a/48387809)

Happy to create a PR with the suggested solution if approved.

### Have you checked if this issue has already been raised?

- [X] I did not find any similar issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by w3cj** [comment]
I am okay with this change. Feel free to make a PR. Be sure to update CONTRIBUTING.md with the steps to create the settings.json file. People will miss out on linting in .svelte files if the settings.json file is missing and they don't already have this setting in their user settings.
