### ISSUE TITLE
Fix parseForESLint is invalid

### ISSUE THREAD

**Issue by Kibujiro** [CodingGarden/listd#58]
### Describe the bug

`npm run lint` is not able to validate `NavTrail.svelte`.  

I tried to reinstall the whole project but I am not able to get the linter to work with this file.

### Screenshots

<img width="565" alt="image" src="https://user-images.githubusercontent.com/123702696/219875577-4bf3be78-40a3-4d23-88f2-aa021b6798bb.png">

### Reproduction

Checkout the latest `main` branch and run `npm run lint`

### Logs

```shell
> listd@0.0.1 lint
> eslint --ext .js,.cjs,.ts,.svelte .


Error while parsing ***\NavTrail.svelte
Line 1, column 8: '>' expected.
`parseForESLint` from parser `@typescript-eslint/parser` is invalid and will just be ignored
```

### Have you checked if this issue has already been raised?

- [X] I did not find any similar issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kibujiro** [comment]
Seems like this is already the case since the merge was done: https://github.com/CodingGarden/listd/pull/38/checks

<img width="362" alt="image" src="https://user-images.githubusercontent.com/123702696/219875781-dd36e734-1003-48a7-a324-4e43d22ff269.png">

**Comment by omar2205** [comment]
1- This is a warning, and most likely it's a result of Svelte +(listd's) ESLint rules. This should be named "Fix `parseForESLint` is invalid`".
2- Good security tip, don't use blur/pixelation to redcat info. A black rectangle works well.

**Comment by MrAmericanMike** [comment]
Same error, in my case the console output is

```
Error while parsing /home/---/Github/CodingGarden/listd/src/routes/NavTrail.svelte
Line 1, column 8: '>' expected.
`parseForESLint` from parser `@typescript-eslint/parser` is invalid and will just be ignored

/home/---/Github/CodingGarden/listd/src/routes/NavTrail.svelte
  44:19  error  Insert `·`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

husky - pre-commit hook exited with code 1 (error)
```

I'm guessing eslint doesn't like the `lang="ts"` in the .svelte file, but even then, if we remove that, it will still complain about some different error.

```
Error while parsing /home/---/Github/CodingGarden/listd/src/routes/NavTrail.svelte
Line 2, column 1: Expression expected.
`parseForESLint` from parser `@typescript-eslint/parser` is invalid and will just be ignored

/home/---/Github/CodingGarden/listd/src/routes/NavTrail.svelte
  44:19  error  Insert `·`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by omar2205** [comment]
I mean, <h1>It's just a warning</h1>

**Comment by w3cj** [comment]
This was fixed by removing `.svelte` from the settings import/parsers section, since `.svelte` files are already handled by the overrides parser.

https://github.com/CodingGarden/listd/blob/1079ae3c5517f16c17270699d2b27ae3835e6912/.eslintrc.cjs#L40
