### ISSUE TITLE
Add prisma-erd-generator (Entity Relationship Diagram)

### ISSUE THREAD

**Issue by omar2205** [CodingGarden/listd#60]
### Describe the problem

I was looking at Prisma's different generators and saw https://github.com/keonik/prisma-erd-generator

![image](https://user-images.githubusercontent.com/1373867/219884560-405d5d44-f520-46fb-872b-0c86895284ca.png)

### Describe the proposed solution

add
```prisma
generator erd {
  provider = "prisma-erd-generator"
}
```

And it will generate `./prisma/ERD.svg` file

### Have you checked if this issue has already been raised?

- [X] I did not find any similar issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by w3cj** [comment]
👍 This looks like a good one. We can add the diagram to the contributing guide as well.
