### ISSUE TITLE
Drop duplicate Tailwind directives

### ISSUE THREAD

**Issue by endigo9740** [CodingGarden/listd#8]
Hey CJ, this is Chris from the Skeleton project.

FYI I caught this in your YouTube VOD today:
https://github.com/CodingGarden/listd/blob/main/src/app.postcss#L2

See this bit in the docs:
https://www.skeleton.dev/guides/tailwind

![image](https://user-images.githubusercontent.com/1509726/214758345-fed35b2b-e212-43bc-88b8-2d5a37a7eb42.png)

It's awesome that Svelte-Add implements these automatically, but unfortunately they do not provide a means to opt out. Leaving dupes like this might cause some issues so probably best to drop them, otherwise they might bite you later!

Hope this helps!

**Comment by w3cj** [comment]
Thanks for letting me know!

**Comment by w3cj** [comment]
Fixed in 3c7005351f84119bf40fdaeb5bb4c960c281a80e
